export const todosciclos = [
{   
    ciclo:1,
    cod_disc:11,
    title:"Algoritmos e lógica de programação",
    ementa:"Conceitos básicos sobre algoritmos e métodos para sua construção. Tipos de dados e variáveis. Álgebra booleana. Estruturas fundamentais de programas: sequencial, condicional e com repetição. Funções. Variáveis compostas homogêneas: vetores e matrizes.",
    objetivo:"Iniciar a formação em programação de computadores por meio de uma linguagem facilitadora do aprendizado de algoritmos, preferencialmente alguma uma linguagem de amplo emprego no mercado",
    notaf: 6.4,
    notam:8.4,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:12,
    title:"Bases da Internet",
    ementa:"Introdução a Internet. Organizações que viabilizam a Internet e a web. Busca de informações. Email, Listas de Email, e Comunicação. Rich Media. Introdução a Redes de computadores. Métodos de compartilhamento de informações. Segurança. Considerações éticas e legais com uso da Internet.",
    objetivo:"Fornecer aos estudantes os conhecimentos básicos sobre a Internet. Quem e como a utiliza. Abordar tópicos para permitir aos estudantes desenvolverem habilidades básicas: email, blogs, navegadores, pesquisa, feeds, FTP, downloads, rich media e social media. Explorar vários métodos de comunicação na Web.",
    notaf: 9.0,
    notam:9.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:13,
    title:"Criação de conteúdo na web",
    ementa:"Teoria. Adequação comunicativa em diferentes situações de interação. Planejamento de produção de conteúdo textual. Escrita e edição de conteúdo para Web",
    objetivo:"Criar conteúdos textuais para páginas da Internet.",
    notaf: 9.3,
    notam:9.7,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:14,
    title:"Design digital",
    ementa:"Apresentar as bases do design gráfico de produção de sítios Internet com emprego de softwares.",
    objetivo:"Projetar mock-ups (cenas) usando o software de design digital, em seguida implementar o projeto como um sítio Internet.",
    notaf: 6.0,
    notam:7.2,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:15,
    title:"Fundamentos de matemática elementar",
    ementa:"Conjuntos Numéricos. Regras de Três. Frações. Porcentagem. Potenciação e Notação Científica. Radiciação. Logaritmos. Polinômios. Fatoração e Produtos Notáveis. Matrizes. Equações e inequações do 1o. e 2o. Graus.",
    objetivo:"Discutir os conceitos básicos de matemática",
    notaf: 7.0,
    notam:7.4,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:16,
    title:"Inglês I",
    ementa:"Introdução à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos da Língua inglesa objetivando desenvolver as quatro habilidades, reading, listening, writing e speaking. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
    notaf: 7.0,
    notam:9.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:17,
    title:"Leitura e produção de textos",
    ementa:"A comunicação na atualidade. Coesão e coerência textuais. Uso e adequação da linguagem. Estratégias de leitura de texto. Produção de texto: resumo acadêmico, resenha crítica, relatório, artigo científico.",
    objetivo:"Ampliar o domínio da comunicação escrita e oral, por meio da aprendizagem e produção de textos existentes no âmbito acadêmico e tecnológico. Favorecer a interpretação de textos relativos à área do curso.",
    notaf: 7.0,
    notam:7.3,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:1,
    cod_disc:18,
    title:"Padrões de projeto de sítios Internet I",
    ementa:"Padrões de projeto para Web. Sintaxe do HTML. Elementos básicos dos conceitos de Web Design. HTML doctypes. Validação do HTML. Boas práticas com HTML e CSS: O CSS, seletores e propriedades. Formulários e estrutura de sítios Internet.",
    objetivo:"Apresentar os fundamentos do HTML (Hypertext Markup Language) com ênfase na semântica do uso dos elementos e nos benefícios do emprego de padrões de codificação. Demonstrar uso do CSS (Cascading Style Sheets) para separar conteúdo e apresentação, de modo a aumentar velocidade do desenvolvimento e as habilidades de design",
    notaf: 7.7,
    notam:8.7,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:21,
    title:"Estruturas de dados",
    ementa:"Revisão dos conceitos básicos de tipos abstratos de dados. Pilhas, filas, alocação dinâmica, recursividade, listas encadeadas, tabelas de espalhamento e árvores. Aplicações das estruturas de dados em problemas computacionais.",
    objetivo:"Aprofundar conhecimentos sobre criação e manipulação de tipos abstratos de dados: listas, pilhas, filas e árvores.",
    notaf: 7.6,
    notam:6.8,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:22,
    title:"Inglês II",
    ementa:"Consolidação da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas desenvolvidas na disciplina Inglês I. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
    notaf: 7.1,
    notam:7.6,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:21,
    title:"Legislação aplicada à Internet",
    ementa:"Introdução ao Direito. Estudo dos impactos na sociedade trazidos pelo computador. Estudo dos princípios éticos relacionados ao uso da Internet. Noções de perícia forense computacional. Aspectos legais de contrato de serviços de TI. Aspectos legais relacionados à Internet. Garantias legais de acesso à informação (dados abertos). Governos eletrônicos. Aspectos legais quanto a negócios intermediados pela Internet e web.",
    objetivo:"Discutir os fundamentos do Direito aplicado à Internet.",
    notaf: 6.5,
    notam:7.5,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:23,
    title:"Matemática discreta",
    ementa:"Apresentar os fundamentos da matemática aplicada ao contexto do curso.",
    objetivo:". Lógica formal. Teoria dos conjuntos. Matrizes. Determinantes. Sistemas Lineares. Relações. Funções. Análise Combinatória",
    notaf: 6.5,
    notam:9.2,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:24,
    title:"Padrões de projeto de sítios Internet II",
    ementa:"Revisão dos padrões de projeto para Web. Tópicos CSS. Esquemas de posicionamento. Elementos flutuantes. Formulários HTML. Elementos de HTML avançado. Técnicas avançadas de reposição de imagem. Seletores avançados do CSS. Microformatos. Técnicas de mosaico de imagens. Resolução de Problemas de layout com uso de depuradores apropriados. Design responsivo. Web semântica. Acessibilidade. Internacionalização.",
    objetivo:"Aprendizado das técnicas avançadas de HTML e CSS para criação de páginas Web de layout sofisticado em conformidade com as diretrizes do W3C. Utilização de microformatos para criar conteúdo semântico e portável. Fornecer ao estudante uma base para criação de sítios acessíveis com aplicação de conceitos do Design Universal para acomodar pessoas com deficiência visual, auditiva, fala, controle motor e distúrbios cognitivos.",
    notaf: 7.7,
    notam:8.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:25,
    title:"Prática de design",
    ementa:"Introdução à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos da Língua inglesa objetivando desenvolver as quatro habilidades, reading, listening, writing e speaking. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
    notaf: 7.5,
    notam: 8.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:2,
    cod_disc:26,
    title:"Redes e Internet",
    ementa:"Internet e os protocolos - detalhamento e implementação dos principais protocolos Internet (DNS, HTTP, SMTP, POP3, NNTP e HTTPS). Identificação de problemas (troubleshooting). Métricas Internet para avaliação e otimização de desempenho de tráfego em redes de computadores. Computação em nuvem.",
    objetivo:"presentar detalhadamente as tecnologias de redes de interesse da Internet. Discutir otimização da comunicação e transmissão de dados nos sítios da Internet.",
    notaf: 6.5,
    notam:8.0,
    aprovadof: true,
    aprovadom: true,
  },
    {
    ciclo:3,
    cod_disc:31,
    title:"Acessibilidade",
    ementa:"Design universal. Usabilidade. Acessibilidade. Tecnologia assistiva. Acessibilidade no HTML e CSS. Testes de acessibilidade. Adobe PDF acessível. Dispositivos de multimídia acessíveis. Scripting acessível. Acessibilidade e dispositivos móveis..",
    objetivo:"Aplicar técnicas de codificação em HTML e CSS. Avaliar acessibilidade relacionada a softwares de uso comum, scripts, dispositivos móveis e legendagem de Rich media.",
    notaf: 7.5,
    notam:8.4,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:32,
    title:"Banco de dados e Internet I",
    ementa:"Conceitos de bases de dados, modelos conceituais e lógicos de dados. Modelo entidaderelacionamento. Modelo de dados relacional. Teoria relacional. Restrições de integridade. Linguagem SQL (Structured Query Language). Projeto de banco de dados no modelo relacional. Normalização.",
    objetivo:"Apresentar os conceitos fundamentais sobre banco de dados e modelagem de dados.",
    notaf:6.2,
    notam:7.7,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:33,
    title:"Engenharia de software para web",
    ementa:"Visão Geral da Engenharia de Software – papel evolutivo, paradigmas, ciclo de desenvolvimento. O processo de desenvolvimento: características e processo de desenvolvimento para aplicações Web. Linguagens gráficas para representação dos modelos. Metodologias ágeis. Mapeamento para implementação. Integração do sistema. Testes: planejamento e tipos. Manutenção. Documentação.",
    objetivo:"Apresentar uma visão ampla e contemporânea da Engenharia de software com ênfase nas metodologias aplicadas ao desenvolvimento para Web",
    notaf: 9.0,
    notam:9.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:34,
    title:"Estatística",
    ementa:"Conceitos estatísticos. Gráficos e tabelas. Distribuição de frequência. Medidas de posição. Medidas de dispersão. Medidas separatrizes. Medidas de assimetria e curtose. Diagrama de dispersão e correlação. Regressão Linear Simples. Coeficiente de correlação. Probabilidade. Distribuições de probabilidade: variável aleatória discreta e contínua.",
    objetivo:"Apresentar Estatística e como utilizá-la para modelar problemas.",
    notaf:6.0,
    notam:10.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:35,
    title:"Inglês III",
    ementa:"Expansão da compreensão e produção oral e escrita por meio de funções sociais e estruturas básicas da língua. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades de construção de blogs e sítios Internet previstas para o semestre.",
    notaf:6.5,
    notam:6.2,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:36,
    title:"Programação de sítios Internet",
    ementa:"a. História do JavaScript. Características do ECMAScript. Melhores práticas de DOM Scripting. Ambientes de testes de JavaScript. ECMAScript: Estrutura léxica, tipos de dados, variáveis de script, expressões e operadores, estruturas de controle, strings e funções de manipulação de strings, objetos e arrays, funções, expressões regulares, objetos Date, Math e Number. Conceitos de programação. DOM Scripting, lado cliente. O modelo de objetos para documentos. Suporte para DOM. Acesso aos elementos do DOM. Classes DOM e sistema de manuseio de bibliotecas e eventos. Eventos temporizados. Manuseio de formulários (validação). Introdução ao AJAX. Propriedades e métodos do objeto Window. Acessibilidade e dispositivos móveis. Erros comuns em DHTML e segurança básica",
    objetivo:"Apresentar aos estudantes conceitos de programação por meio de ECMAScript (European Computer Manufacturers Association - ECMA) – JavaScript - e Document Object Model (DOM) scripts. Apresentar a história ECMAScript, e seu papel em sítios Internet contemporâneos e aplicações Web. Descrever como Scripts básicos e intermediários são criados para resolver problemas comuns de interface. Aprender a avaliar as bibliotecas existentes e scripts para que possam tomar decisões sobre sua aplicabilidade em uma dada tarefa. Aprender as melhores práticas, técnicas de DOM Scripting (JavaScript).",
    notaf:9.4,
    notam:8.1,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:3,
    cod_disc:37,
    title:"Servidores e seus sistemas operacionais",
    ementa:"Identificação dos componentes para montar um servidor, compatibilidade, detalhes sobre as especificações de cada componente, identificação e correção de problemas. Instalação e configuração de softwares (aplicativos gerais, gerenciadores de bancos de dados e sistemas operacionais). Compreender os conceitos, mecanismos e funcionamento dos Sistemas operacionais modernos. Criação de partições, formatação de discos, instalação de drivers. Virtualização de servidores para a implementação de serviços de gerenciamento de usuários, serviços de comunicação e de armazenamento de dados através da utilização de uma intranet composta por aplicativos da internet. Configuração de aplicações e serviços Web. Migração de Web sites e aplicações. Configuração de sites seguros (Controle de acesso e Autenticação).",
    objetivo:"Apresentar os recursos tecnológicos empregados em servidores de redes de computadores.",
    notaf:8.5,
    notam:8.5,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:41,
    title:"Banco de dados e Internet II",
    ementa:"Tipos de Junções (join). Subconsultas (Subqueries). Criação, implementação e utilização de procedimentos armazenados (stored procedures), gatilhos (triggers), funções, cursores, visões (view). Linguagem de Controle de Dados. Transações. Bancos de dados orientados a objetos. Bancos de dados multimídia.",
    objetivo:"Apresentar recursos avançados para criação de aplicativos com Banco de dados",
    notaf:8.7,
    notam:9,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:42,
    title:"Desenvolvimento para servidores I",
    ementa:"PHP histórico e emprego. Instalação e configuração básica do PHP e um IDE. Sintaxe básica do PHP. Usando o PHP como um mecanismo de modelo simples. Panorama das melhores práticas com PHP. Conceitos de programação HTTP. Codificação de caracteres. Localidades, fusos horários e funções de tempo. Strings. Uso de Array e funções de matriz. Orientação a objetos em PHP (Classes, objetos, herança, encapsulamento, polimorfismo, agregação, composição e métodos). Tratamento de exceções de erro. Arquitetura do lado do servidor. Manipulação de dados postados. Enviando e-mail. Sessões e autenticação. Cookies. Arquivo manuseio e armazenamento de dados em arquivos de texto. Gerenciador de banco de dados e suas funções. Frameworks. Web Services, API, RSS, JSON e Ajax. Hospedagem compartilhada.",
    objetivo:"Esta disciplina fornecerá uma visão geral da linguagem script PHP associado a um gerenciador de banco de dados que utilize a linguagem SQL e como usar essas tecnologias para gerar sites dinâmicos. Introduzir práticas de codificação seguras",
    notaf:8.0,
    notam:6.2,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:43,
    title:"Inglês IV ",
    ementa:"Aprofundamento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmico-profissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as atividades do semestre, inclusive na elaboração dos artigos técnicos.",
    notaf:8.7,
    notam:8.5,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:44,
    title:"Projeto de navegação e Interação.",
    ementa:"Arquitetura de Informação. Levantamento de requisitos / conteúdo Web. Definição do projeto: organização e estrutura de interação. Estrutura de processo. Design de interação. O princípio do projeto da UX. Definição do produto e público. Pesquisa de usuário. Personas. Métodos de investigação e avaliação. Projeto conceitual. Design detalhado. Design da experiência do usuário e otimização de site de busca. Transição da definição para a projeção. Mapas do site e fluxos de tarefa. Prototipagem light. Wireframes e anotações. Teste do design com usuários. Transição do design ao desenvolvimento.",
    objetivo:"Apresentar aos estudantes os princípios fundamentais e metodologias de Arquitetura da Informação e do Design da interação com usuário para definir um projeto de software para Internet em termos de sua finalidade, escopo, audiência, elementos principais, fluxos de tarefas, layout, etc. Padrões de projeto. Frameworks serão introduzidos a fim de criar interfaces que mapeiem as expectativas dos usuários e melhorem a experiência do usuário (UX), incluindo levantamentos de requisitos com usuários, avaliação de conteúdo e de organização, documentação de processos no âmbito dos sistemas, definição de estruturas organizacionais e desenvolvimento de protótipos interativos..",
    notaf:8.0,
    notam:8.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:45,
    title:"Prática de Gestão de Projetos",
    ementa:"Definição de projeto segundo concepção difundida pelas melhores práticas de gestão de projetos. Histórico do desenvolvimento do conjunto de conhecimentos de gestão de projetos. O ciclo de vida de um projeto (concepção, programação, execução, controle e encerramento). Os fatores de sucesso e insucesso de projetos e sua mensuração. Componentes da gestão de projetos: projeto, clientes e equipe. Plano de qualidade. Gestão de integração, escopo, tempo, custos, riscos, recursos humanos, comunicação e qualidade de projetos.",
    objetivo:"Conhecer e aplicar técnicas, métodos e ferramentas para uma gestão eficaz de projetos nas suas diferentes facetas, incluindo a equipe de gestão e interações com o cliente. Discutir gestão de equipes multidisciplinares em design e produção de sítios Internet.",
    notaf:8.7,
    notam:8.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:46,
    title:"Segurança em sistemas para Internet",
    ementa:"Conceitos básicos de segurança da informação. Criptografia, conceitos e uso. Segurança da infraestrutura e das aplicações. Tópicos em desenvolvimento de aplicações seguras. Aspectos legais: validade do documento eletrônico, assinaturas digitais, datação e Infraestrutura de Chave Pública. Aspectos gerenciais: metodologias práticas e normativas referentes às boas práticas de segurança da informação em sistemas diversos, norma ISO/IEC 17799 (família 27.000). Preparação para a implementação, manutenção, monitoramento e melhoria da segurança da informação consistente com a cultura organizacional. Requisitos de segurança da informação: análise; avaliação e gestão de riscos.",
    objetivo:"Apresentar e discutir as questões relativas à segurança da informação.",
    notaf:9.7,
    notam:9.7,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:4,
    cod_disc:47,
    title:"Tópicos especiais em sistemas para Internet I",
    ementa:"Recursos e aplicações da tecnologia escolhida.",
    objetivo:"Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade",
    notaf: 10.0,
    notam:10.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:5,
    cod_disc:51,
    title:"Desenvolvimento para Servidores II",
    ementa:"Conceitos e evolução das tecnologias de programação de servidores. Recursos da linguagem escolhida para servidores na Internet. Padrões de projetos. Integração com sistemas (Google Maps API, Twitter, entre outros)",
    objetivo:"Desenvolver um site completo de e-commerce ou outro tipo de negócio na Internet usando uma linguagem apropriada a servidores, banco de dados e padrões de projeto.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:5,
    cod_disc:52,
    title:"Desenvolvimento para dispositivos móveis I",
    ementa:"Introdução e conceitos. Recursos disponíveis para dispositivos móveis na linguagem de marcação de textos. Uso de algum ambiente de desenvolvimento: configuração do ambiente; emulação de dispositivos móveis nos computadores pessoais; interface gráfica; serviços disponíveis; banco de dados nos dispositivos. Desenvolvimento de aplicações que utilizam dados de geolocalização. Integração entre sistemas remotos.",
    objetivo:"Apresentar as tecnologias de desenvolvimento de aplicativos para dispositivos móveis.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:5,
    cod_disc:53,
    title:"Inglês V",
    ementa:"Aprofundamento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Apoiar as demais atividades dos estudantes na criação de sítios Internet.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:5,
    cod_disc:54,
    title:"Negócios e Marketing Eletrônicos",
    ementa:"Conceitos de marketing e de marketing digital. O comportamento do consumidor on-line. Marketing de conteúdo. Marketing nas mídias sociais. E-mail marketing. Marketing viral. Publicidade on-line. Pesquisa de marketing on-line. Marketing e os negócios na Internet. Estudos de caso.",
    objetivo:"Apresentar e discutir as questões do marketing na era da Internet. Abordar as principais estratégias, ações, ferramentas e mídias presentes na Web.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:5,
    cod_disc:55,
    title:"Projeto de prototipagem e testes de Usabilidade",
    ementa:"Conceitos, métodos de prototipagem e ferramentas de teste de protótipos. Conceitos de usabilidade e estratégias de design. Métodos de teste de usabilidade. Planejamento de teste de usabilidade. Recrutamento. Projeto de usabilidade. Plano de teste. Sessão de teste de usabilidade. Análise de dados. Comunicação dos resultados. Variação de técnicas.",
    objetivo:"Aprofundar os conceitos de design da usabilidade e métodos de ensaio para mídia interativa. Usabilidade baseada na adaptação de design de interface para uma experiência do usuário mais eficaz. Apresentar e usar diferentes métodos e ferramentas de prototipagem para explorar com os colegas de equipe ou clientes: conceitos de design, comunicação e testes de usabilidade.",
    notaf: 8.2,
    notam:8.2,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:5,
    cod_disc:56,
    title:"Projeto do trabalho de graduação em Sistemas",
    ementa:"Conceito de portfólio no âmbito da educação superior. Planejamento e organização de portfólios.",
    objetivo:"Apoiar o estudante na organização de seu portfólio de projetos desenvolvidos ao longo do curso.",
    notaf:9.0,
    notam:9.0,
    aprovadof: true,
    aprovadom: true,
  },
  {
    ciclo:5,
    cod_disc:57,
    title:"Tópicos Especiais em Sistemas para Internet II",
    ementa:"Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.",
    objetivo:"Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:61,
    title:"Arquitetura orientada a serviços",
    ementa:"Construção de aplicações por meio da utilização de arquitetura orientada a serviços – SOA (Service-Oriented Architecture) e das principais tecnologias Web Services.",
    objetivo:"Discutir tecnologias associadas a SOA (Services Oriented Architecture)",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:62,
    title:"Criação de empresas para Internet",
    ementa:"a. O planejamento de um projeto de negócios para Internet. Implantação e implementação de projetos de negócios. Administração de custos e dos prazos de implantação em projetos. Identificação de oportunidades de investimentos. Analise de mercado. Desenvolvimento e implementação de negócios. Finanças de um projeto de Investimentos. Análise de sensibilidade. Empreendedorismo e inovação: liderança estratégica. Administração participativa e os novos modelos de administração. Principais funções administrativas e respectivos sistemas de informação. Mecanismos e procedimentos para criação de empresas. Criação de empresas focadas na Internet. Computação em Nuvem - estratégias e modelos. Formular e selecionar estratégias e modelos baseados em computação em nuvem. Análise dos pontos positivos e negativos dessa abordagem de negócios.",
    objetivo:"Fornecer ao estudante o estado da arte a respeito dos conhecimentos sobre empreendedorismo, inovação e criação de novos negócios para Internet.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:63,
    title:"Desenvolvimento para dispositivos móveis II",
    ementa:"Uso de algum ambiente de desenvolvimento (framework) em plataforma proprietária: configuração do ambiente; emulação de dispositivos móveis nos computadores pessoais; interface gráfica; serviços disponíveis; banco de dados nos dispositivos. Desenvolvimento de aplicativos com uso de frameworks",
    objetivo:"Discutir tecnologias de desenvolvimento de aplicativos para dispositivos móveis em alguma plataforma proprietária.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:64,
    title:"Inglês VI",
    ementa:"Aprimoramento da compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas. Ênfase na oralidade, atendendo às especificidades acadêmicoprofissionais da área e abordando aspectos socioculturais da língua inglesa.",
    objetivo:"Apresentar os recursos do idioma necessários à compreensão e produção oral e escrita por meio da integração das habilidades linguístico-comunicativas.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:65,
    title:"Projeto de encontrabilidade",
    ementa:"Teoria Geral. Marcação para encontrabilidade. Microformatos. Conteúdo. Rede Social. Estratégias Server-Side. Como evitar armadilhas de encontrabilidade. Pesquisas. Análises.",
    objetivo:"Explorar estratégias que direcionam o tráfego para um site, ajudam os usuários a encontrar conteúdo dentro de um site e encorajam consultas de retorno. Discutir os Métodos de Otimização de Search Engine (SEO), estratégias de marketing, análise de tráfego e teoria em torno comportamento de busca. Investigar as relações entre usabilidade, acessibilidade, arquitetura da informação, marketing, e encontrabilidade, a fim de implementar estratégias para a criação de conteúdo encontrável.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:66,
    title:"Projeto do trabalho de graduação em Sistemas",
    ementa:"Conceito de portfólio no âmbito da educação superior. Planejamento e organização de portfólios.",
    objetivo:"Apoiar o estudante na organização de seu portfólio de projetos desenvolvidos ao longo do curso.",
    notaf:0,
    notam:0,
    aprovadof: false,
    aprovadom: false,
  },
  {
    ciclo:6,
    cod_disc:67,
    title:"Tópicos Especiais em Sistemas para Internet III",
    ementa:"Recursos e aplicações da tecnologia escolhida.",
    objetivo:"Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.",
    notaf:8.8,
    notam:0,
    aprovadof: true,
    aprovadom: false,
  }
]